spring:
  profiles:
    include: db, jwt

server:
  port: 8080

springdoc:
  api-docs:
    path: /api-docs
  default-produces-media-type: application/json;charset=UTF-8
  default-consumes-media-type: application/json;charset=UTF-8
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger.html